name: Black Format Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_NAME: qiyu_api


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install black
        run: |
          python -m pip install black

      - name: Run black
        run: |
          black ${{ env.PROJECT_NAME }}
